case_ids:
- case_000
- case_001
- case_002
- case_003
- case_004
- case_005
- case_006
- case_007
git_hash: 7f41263763784cb3258b919deb00bc667b77131b
img_dir: Dataset/Images
invert_masks: false
mask_dir: Dataset/Segmentations
model_str: unet
model_weights_path: model_weights/epoch_10_model.pt
only_foreground_slices: false
output_dir: test_all_train_slices
quick_test: false
save_segmentations: true
seed: 42
