name: mphil_medical_imaging_cw
channels:
  - defaults
dependencies:
  - numpy
  - flake8
  - pytest
  - pandas
  - black
  - sphinx
  - matplotlib
  - pre-commit
  - scipy
  - tqdm
  - pip
  - ipykernel
  - pip:
    - torch
    - torchvision
    - torchmetrics
    - accelerate
    - wandb
    - pydicom
    - nibabel
