case_ids:
- Case_008
git_hash: a38c9fdcf483ab6e9ada38ec00232f3ae3972a55
img_dir: Dataset/Images
invert_masks: false
mask_dir: Dataset/Segmentations
model_str: unet
model_weights_path: trained_model.pt
only_foreground_slices: false
output_dir: model_evaluation/docker
quick_test: false
save_segmentations: false
seed: 42
